### ISSUE TITLE
mine error if mine coin more than 5

### ISSUE THREAD

**Issue by 330247153** [quetzalcoatl/blagominer#10]
mine error if mine coin more than 5  ??

the mine software will exit ??

**Comment by quetzalcoatl** [comment]
Strange, it should not. I admit I tested it only up to 4 coins, and I expected some visual glitches on more than 4 coins, but it should not just exit.

Thanks for reminding me about that, I'll check what's up and will try to fix it.

**Comment by TheNetWhiz** [comment]
Any updates on a fix? Have a 5th coin to mine now and it crashes.
