### ISSUE TITLE
Option to start blago in "CLI" mode, without its own UI

### ISSUE THREAD

**Issue by felixbrucker** [quetzalcoatl/blagominer#11]
**Is your feature request related to a problem? Please describe.**
When starting blago it forks itself into a UI one can't work with like a regular cli tool. This means one can't start it as a child process and retrieve its stdout properly.

**Describe the solution you'd like**
Being able to start the miner and it works similar to how scavenger works, you can start it as a child process etc. How to toggle the UI/non-UI version is up to you, could be a startup flag, or a config option, or something else.

**Additional context**
Ultimate goal is to make multi blago work with foxy-miner (which would just act like a stupid proxy), but it handles stats retrieval (speed, progress, current block scanning etc) from the child process (std) output.

**Comment by quetzalcoatl** [comment]
Still working on that, almost done (--')
RL things and other projects eat much of my free time, but I didn't forget!
