### ISSUE TITLE
CRLF visual bug

### ISSUE THREAD

**Issue by Kafkamorph** [quetzalcoatl/blagominer#20]
v2.300004.0 Release has this awkward ^A ending on each line. 
Looks weird.

![aa](https://user-images.githubusercontent.com/2609870/84321647-74f0a600-ab6b-11ea-9b83-9ef92a47fa09.PNG)

**Comment by Kafkamorph** [comment]
![aa2](https://user-images.githubusercontent.com/2609870/84321906-fb0cec80-ab6b-11ea-8e17-5a44ca588b93.PNG)

This one, too.

**Comment by quetzalcoatl** [comment]
Hm.. interesting. That's not a line you see usually. Have you turned on the `debug` mode by chance?

**Comment by quetzalcoatl** [comment]
Whoa. I forgot to add a parameter, it just prints random trash. Thanks, that actually could crash blago.

note to self: 
xxx::debugWorkerStats(), specialReadMode, see comment re last %s, no such param passed to printToConsole
