### ISSUE TITLE
Invalid plot sizes on initial plot dump 

### ISSUE THREAD

**Issue by quetzalcoatl** [quetzalcoatl/blagominer#23]
![image](https://user-images.githubusercontent.com/1564880/84994118-7f520780-b14a-11ea-9690-54d16d0db1f8.png)

Initial dump of the map of all plot directories list all of them as `0 GiB`  
However, the total size right after that, and also the total during scanning-progress seem fine.

**Comment by zjhxmjl** [comment]
Hi,guy,is there any solutions for this bug?

**Comment by quetzalcoatl** [comment]
@zjhxmjl that needed a patch in the code, I patched it already but didn't publish a new version, and right now I got stuck while refactoring the whole thread management and implementing burst-stratum.. soo.. it's gonna stay for another while unless it's a critical thing for you for some reason (is it?)
