### ISSUE TITLE
// TODO: what does the Log() do before Log_init() is executed?

### ISSUE THREAD

**Issue by Blagodarenko** [quetzalcoatl/blagominer#25]
https://github.com/quetzalcoatl/blagominer/blob/fdd17417c85e2eb0e5d15ae5ba8181a0ceae362c/blagominer/blagominer.cpp#L338

yes, its need to fix, originaly its was the first command, which creates the file. 
https://github.com/Blagodarenko/miner-burst/blob/140756ad30361a0a44d5f9d7ec8db9e8684863fc/miner.cpp#L159

**Comment by quetzalcoatl** [comment]
Oooh I see it now, thank you!
