### ISSUE TITLE
Can not parse result from pools

### ISSUE THREAD

**Issue by TheNetWhiz** [quetzalcoatl/blagominer#3]
**Describe the bug**
After miner started and did nothing, I checked the logs and found the following:

----

21:39:35.517 *! GMI BHD: error parsing JSON message from pool: HTTP/1.0 200 OK\r\nAccept-Ranges: bytes\r\nContent-Length: 1381\r\nContent-Type: text/html; charset=utf-8\r\nLast-Modified: Thu, 13 Dec 2018 04:10:57 GMT\r\nDate: Fri, 12 Jul 2019 01:39:35 GMT\r\n\r\n<!DOCTYPE html><html style="width: 100%%;height: 100%%;" lang=zh_CN class=pc><head><title>HD Miner</title><meta charset=utf-8><meta content=no-cache http-equiv=Pragma><meta content=portrait name=x5-orientation><meta content=portrait name=screen-orientation><meta content=yes name=apple-touch-fullscreen><meta content=yes name=apple-mobile-web-app-capable><meta content=black name=apple-mobile-web-app-status-bar-style><meta content=yes name=apple-mobile-web-app-capable><meta content="telephone=no,email=no" name=format-detection><meta content="IE=Edge,chrome=1" http-equiv=X-UA-Compatible><meta name=full-screen content=true><meta name=x5-fullscreen content=true><meta name=360-fullscreen content=true><meta name=referrer content=no-referrer><meta name=apple-mobile-web-app-capable content=yes><meta name=viewport 
21:39:35.519 *! GMI Burst: error parsing JSON message from pool: HTTP/1.0 302 Found\r\nDate: Fri, 12 Jul 2019 01:38:04 GMT\r\nConnection: Close\r\nServer: creepMiner 1.9.0\r\nContent-Length: 0\r\nLocation: /login\r\n\r\n
21:39:35.733 UPDATE CHECKER: The miner is up to date (2.300001.1)
21:39:36.481 *! GMI BHD: error parsing JSON message from pool: HTTP/1.0 200 OK\r\nAccept-Ranges: bytes\r\nContent-Length: 1381\r\nContent-Type: text/html; charset=utf-8\r\nLast-Modified: Thu, 13 Dec 2018 04:10:57 GMT\r\nDate: Fri, 12 Jul 2019 01:39:36 GMT\r\n\r\n<!DOCTYPE html><html style="width: 100%%;height: 100%%;" lang=zh_CN class=pc><head><title>HD Miner</title><meta charset=utf-8><meta content=no-cache http-equiv=Pragma><meta content=portrait name=x5-orientation><meta content=portrait name=screen-orientation><meta content=yes name=apple-touch-fullscreen><meta content=yes name=apple-mobile-web-app-capable><meta content=black name=apple-mobile-web-app-status-bar-style><meta content=yes name=apple-mobile-web-app-capable><meta content="telephone=no,email=no" name=format-detection><meta content="IE=Edge,chrome=1" http-equiv=X-UA-Compatible><meta name=full-screen content=true><meta name=x5-fullscreen content=true><meta name=360-fullscreen content=true><meta name=referrer content=no-referrer><meta name=apple-mobile-web-app-capable content=yes><meta name=viewport 
21:39:36.481 *! GMI Burst: error parsing JSON message from pool: HTTP/1.0 302 Found\r\nDate: Fri, 12 Jul 2019 01:38:05 GMT\r\nConnection: Close\r\nServer: creepMiner 1.9.0\r\nContent-Length: 0\r\nLocation: /login\r\n\r\n
21:39:37.436 *! GMI BHD: error parsing JSON message from pool: HTTP/1.0 200 OK\r\nAccept-Ranges: bytes\r\nContent-Length: 1381\r\nContent-Type: text/html; charset=utf-8\r\nLast-Modified: Thu, 13 Dec 2018 04:10:57 GMT\r\nDate: Fri, 12 Jul 2019 01:39:37 GMT\r\n\r\n<!DOCTYPE html><html style="width: 100%%;height: 100%%;" lang=zh_CN class=pc><head><title>HD Miner</title><meta charset=utf-8><meta content=no-cache http-equiv=Pragma><meta content=portrait name=x5-orientation><meta content=portrait name=screen-orientation><meta content=yes name=apple-touch-fullscreen><meta content=yes name=apple-mobile-web-app-capable><meta content=black name=apple-mobile-web-app-status-bar-style><meta content=yes name=apple-mobile-web-app-capable><meta content="telephone=no,email=no" name=format-detection><meta content="IE=Edge,chrome=1" http-equiv=X-UA-Compatible><meta name=full-screen content=true><meta name=x5-fullscreen content=true><meta name=360-fullscreen content=true><meta name=referrer content=no-referrer><meta name=apple-mobile-web-app-capable content=yes><meta name=viewport 

----

**To Reproduce**
Configured miner.conf with same parameters from previous working version. Miner starts but does not parse mining info.

**Comment by quetzalcoatl** [comment]
It all seems like the server/port/https/rooturl were misconfigured.

GMI BURST states 302 and /login, so the pool site tries to do a redirect to a login page. I can only guess that the rooturl may be wrong, or that some X-* header is missing (account? password? I dont know, I haven't used creepMiner).

GMI BHD on the other hand says something about HD Miner. Are you connecting to a HDProxy, or to the HDPool itself? HDPool is not supported for direct connections (yet), as it uses another protocol over websockets. HDProxy is still needed here for translating it back to 'normal'.

If above notes doesn't help you in resolving this issue, please consider sending me your `miner.conf` file so I can inspect the problems first hand.

Or, there is a slight chance that the problems you have are related to a bug in code responsible for reading configuration. I just fixed one, but it usually ended up with "JSON parse error" and total crash at startup.. so your case doesn't look like that.

**Comment by quetzalcoatl** [comment]
hey @TheNetWhiz, did you solve it? does the problem persist in the newest version of HDMiner?

**Comment by TheNetWhiz** [comment]
Yes, it seems fixed. Thank you.
