### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by knightjohn257** [quetzalcoatl/blagominer#7]
I am new user by vs,when i creat the blagominerv2.300001.1.exe(for Stability vision)by code,i can't creat the exe with three Vs dynamic library(libcurl.dll pdcurses.dll zlib1.dll find from release),i did not found zlib1.dll,just use zlib.dll,so i did not finish creat exe ,then i ceart exe by pdcurses.lib(from PDCurses34.3.4.0.1)  zlibstatic.lib(from zlib-vc140-static-64.1.2.11)  libcurl.lib(from curl.7.30.0.2).Is there any question about stability from my blagominerv2.300001.1? And what is vs dynamic library vision using by blagominer's author，waiting for your re~

**Comment by quetzalcoatl** [comment]
Hi there! What do you mean by:

> when i creat the blagominerv2.300001.1.exe(for Stability vision)by code,i can't creat the exe with three Vs dynamic library(libcurl.dll pdcurses.dll zlib1.dll find from release

I really can't understand. Could you elaborate a bit? What are you trying to do and how?
If you want to run blagominer, just grab a ZIP from the releases, and all files are there, both exe and dlls. Or maybe you are trying to build it from scratch?

> And what is vs dynamic library vision using by blagominer's author

uh... and this one I totally don't get, sorry.

**Comment by quetzalcoatl** [comment]
Hey @knightjohn257 did you solve that problem?

**Comment by quetzalcoatl** [comment]
Closed due to inactivity
